### ISSUE TITLE
请问 边缘局域网需要有公网ip吗？

### ISSUE THREAD

**Issue by hhstu** [openyurtio/raven#19]

**Comment by njucjc** [comment]
目前需要至少一个公网出口IP

**Comment by njucjc** [comment]
目前至少需要一个出公网的IP

**Comment by hhstu** [comment]
我们目前的场景是，云在 阿里云，阿里云可以有公网 ip， 边在停车场，停车场目前没有公网 ip，仅仅是 4G 网。也就是目前还无法使用 raven 打通云边容器网络对吧

**Comment by rambohe-ch** [comment]
> 我们目前的场景是，云在 阿里云，阿里云可以有公网 ip， 边在停车场，停车场目前没有公网 ip，仅仅是 4G 网。也就是目前还无法使用 raven 打通云边容器网络对吧

@hhstu  A public ip should be provided on cloud nodes or edge nodes. so i think this case can be supported now because cloud nodes have a public ip.

**Comment by hhstu** [comment]
我在配置上还是有点蒙蔽，可否再补充三个场景的 demo：

- 场景一
  云上三个 master 节点，每个节点都只有一个 网卡，只有一个 ip
  边缘一个节点，边缘节点可以访问所有云上节点的 ip

- 场景二
  云上三个 master 节点，n 个 work 节点，节点均为阿里云服务器，所有节点各有一个网卡绑定的私网ip 、所有节点各有一个外部映射的公网 ip
  边缘一个节点，边缘节点可以访问所有云上节点的 公网ip，但不能访问云上的私网 ip

- 场景三
  云上三个 master 节点，n 个 work 节点，节点均为阿里云服务器，所有节点都有一个网卡绑定的私网ip ，但仅各个master节点有外部映射的公网 ip
  边缘一个节点，边缘节点可以访问所有云上节点的 公网ip，但不能访问云上的私网 ip

**Comment by guangxuli** [comment]
Hi guys, I also have the same question, whether the edge node needs to have a public IP, or the edge node needs to be able to access the public IP of the cloud.
@rambohe-ch

**Comment by njucjc** [comment]
> 

1. 场景一master是在nat后的话暂时还不支持
2. 场景二和三看描述都是可支持的，总体的原则是将所有私网IP内部可达的节点用一个Gateway CR来管理，有公网IP的endpoint的natEnable值设为false即可，比如场景二，我假设master直接内网可达，worker之间也是内网可达，那么相应的Gateway CR可以像下面这样写：
```bash
$ cat <<EOF | kubectl apply -f -
apiVersion: raven.openyurt.io/v1alpha1
kind: Gateway
metadata:
  name: gw-master
spec:
  backend: libreswan
  endpoints:
    - nodeName: master-1
      privateIP: <master-ip-1>
      natEnabled: false
    - nodeName: master-2
      privateIP: <master-ip-2>
      natEnabled: false
    - nodeName: master-3
      privateIP: <master-ip-3>
      natEnabled: false
---
apiVersion: raven.openyurt.io/v1alpha1
kind: Gateway
metadata:
  name: gw-worker
spec:
  backend: libreswan
  endpoints:
    - nodeName: worker-1
      privateIP: <worker-ip-1>
      natEnabled: false # 看是否有公网ip，有为false，无为true
      
---
apiVersion: raven.openyurt.io/v1alpha1
kind: Gateway
metadata:
  name: gw-edge
spec:
  backend: libreswan
  endpoints:
    - nodeName: edge-1
      privateIP:  <edge-ip-1>
      natEnabled: true

EOF
```

**Comment by BSWANG** [comment]
There is two type of  `Public IP`:
* Egress-only Public IP:  4G/NATGW/NAT-router……   
* bi-direction Public IP:  EIP/fixed-ip/dmz-ip……

The cloud node need `bi-direction Public IP` , the edge node just need `Egress-only Public IP`.

> Reference in new is

**Comment by BSWANG** [comment]
> 我们目前的场景是，云在 阿里云，阿里云可以有公网 ip， 边在停车场，停车场目前没有公网 ip，仅仅是 4G 网。也就是目前还无法使用 raven 打通云边容器网络对吧

4G网是有出公网IP的，这种是可以打通到云上的双向公网IP，也是可以打通容器网络的。

**Comment by hhstu** [comment]
publicIP 目前是必填，这设计有问题吗?  @njucjc

**Comment by njucjc** [comment]
> publicIP 目前是必填，这设计有问题吗? @njucjc

看错了吧，目前PublicIP不是必填 
[Gateway](https://github.com/openyurtio/raven-controller-manager/blob/main/pkg/ravencontroller/apis/raven/v1alpha1/gateway_types.go)

**Comment by hhstu** [comment]
https://github.com/openyurtio/raven-controller-manager/blob/main/config/setup/all_in_one.yaml   看下这个 openapi 校验 @njucjc

**Comment by njucjc** [comment]
> https://github.com/openyurtio/raven-controller-manager/blob/main/config/setup/all_in_one.yaml 看下这个 openapi 校验 @njucjc

crd的yaml不是用的这个，运行make push的时候会重新生成，详情看一下README

**Comment by hhstu** [comment]
> > https://github.com/openyurtio/raven-controller-manager/blob/main/config/setup/all_in_one.yaml 看下这个 openapi 校验 @njucjc
> 
> crd的yaml不是用的这个，运行make push的时候会重新生成，详情看一下[README](https://github.com/openyurtio/raven-controller-manager/blob/main/README.md)

了解，这可以理解为完全面向内测了

**Comment by hhstu** [comment]
close
