### ISSUE TITLE
[feature request]  provides the capabilities to execute kubectl exec/logs to edge nodes

### ISSUE THREAD

**Issue by njucjc** [openyurtio/raven#31]
take over the capabilities of YurtTunnel

**Comment by rambohe-ch** [comment]
@njucjc Migrate yurt-tunnel into raven is divided into two issues, the details as following:
1. merge yurt-tunnel-server/agent into raven except ANP. #40 
2. enhance ANP for yurt-tunnel in raven.  #41

**Comment by zzguang** [comment]
I suggest to close this issue because raven l7 solution has already covered this feature.
