### ISSUE TITLE
can not get public ip

### ISSUE THREAD

**Issue by luckymrwang** [openyurtio/raven#35]
When I deploy raven following the tutorial, the pod of raven's console print error message `error get public ip by any of the apis: [https://api.ipify.org https://api.my-ip.io/ip https://ip4.seeip.org]`. 

I think that it's better to configure the public ip by node annotation when the edge node is deploy in inner network or not.

**Comment by njucjc** [comment]
your can config public ip at gateway cr manually.
![image](https://user-images.githubusercontent.com/15940738/170451704-ba1e9ce6-6e38-4f70-9ff9-2101c9bf2924.png)

**Comment by luckymrwang** [comment]
@njucjc ok
