### ISSUE TITLE
Raven support passing through NAT 

### ISSUE THREAD

**Issue by ujnzxw** [openyurtio/raven#45]
In many edge computing cases, the edge nodes must deploy in a local NAT network. one or more edge nodes in this local NAT network has permission to access the remote Cloud API server. However, the Cloud nodes cannot access the edge node initiatively.
As a professional network solution for edge computing, Raven needs to support this typical scenario as soon as possible.

**Comment by ujnzxw** [comment]
@njucjc Thanks for your reply. 
Actually, I did not test it in the Raven network. The official document described below may be incorrect:
https://openyurt.io/docs/core-concepts/raven/#5-%E6%9C%AA%E6%9D%A5%E8%AE%A1%E5%88%92
It says Reven will support the NAT mode in the future.

**Comment by njucjc** [comment]
> 

It means NAT-to-NAT passing through actually that directly without central forwarding. I'm sorry for making you misunderstood.

**Comment by ujnzxw** [comment]
@njucjc No problem. 
NAT-to-NAT model is also a valuable feature for us.
Does that mean when there is no network connection between Cloud and nodepool1&nodepool2, but nodepool1's service/pod can communicate with nodepool2's service/pod?
If yes, this is a very meaningful feature.

**Comment by njucjc** [comment]
> @njucjc No problem. NAT-to-NAT model is also a valuable feature for us. Does that mean when there is no network connection between Cloud and nodepool1&nodepool2, but nodepool1's service/pod can communicate with nodepool2's service/pod? If yes, this is a very meaningful feature.

yes
