### ISSUE TITLE
Does raven support kubeproxy ipvs now and which image should i choose?

### ISSUE THREAD

**Issue by whisperzzZ** [openyurtio/raven#55]
The related issue #16  has been moved to done in roadmap 0.2。
so if I want to deploy raven on my cluster which uses kubeproxy ipvs mode , which image should I choose?
raven-agent:latest Last pushed 2 months ago   and   raven-agent:main seems the right image?

**Comment by whisperzzZ** [comment]
thanks a lot!

**Comment by njucjc** [comment]
Is it convenient to ask which scene you are using raven in?
