### ISSUE TITLE
[Question] How to avoid entering nodes manually?

### ISSUE THREAD

**Issue by batthebee** [openyurtio/raven#89]
If I understand the documentation correctly, nodes must be both labeled and entered into the gateway spec. The labeling of the nodes can be done when registering a node. After that I have to manually adjust the gateway spec. This makes automation very difficult. 

Are there currently other ways to do this, e.g. only via the labels?  What is the reason for the double entry?

**Comment by njucjc** [comment]
Only gateway nodes should be entered into the gateway spec

**Comment by njucjc** [comment]
for new node added to `gw-wlcb` gateway，just run：
`kubectl label nodes $(nodeName) raven.openyurt.io/gateway=gw-wlcb`
if this node is not a candidate gateway node, you do not need to enter it to gateway spec
